# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('details', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('M', 'Missed')], default='P', max_length=2)),
                ('labels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.Label')),
            ],
        ),
    ]
