# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20161012_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
