# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todolistmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoListManager',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='labels',
            new_name='label',
        ),
    ]
