# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 16:26
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):

    TodoList = apps.get_model("todoapp", "TodoList")

    for todo in TodoList.objects.all():
        if todo.status == 'P':
            todo.status = 'Pending'
        elif todo.status == 'C':
            todo.status = 'Completed'
        elif todo.status == 'M':
            todo.status = 'Missed'
        todo.save()

def backward(apps, schema_editor):

    TodoList = apps.get_model("todoapp", "TodoList")

    for todo in TodoList.objects.all():
        if todo.status == 'Pending':
            todo.status = 'P'
        elif todo.status == 'Completed':
            todo.status = 'C'
        elif todo.status == 'Missed':
            todo.status = 'M'
        todo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20161016_1622'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
